name: Publish Python Wheel to ghcr.io

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          pip install build

      - name: Build wheel
        run: |
          python -m build
      - name: Install ORAS CLI
        run: |
          curl -LO https://github.com/oras-project/oras/releases/latest/download/oras_$(uname -s)_$(uname -m).tar.gz
          tar -xvzf oras_*.tar.gz -C /usr/local/bin oras

      - name: Login to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Push wheel to ghcr.io
        run: |
          WHEEL_FILE=$(ls dist/*.whl | head -n 1)
          oras push ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
            --artifact-type application/vnd.python.whl \
            $WHEEL_FILE
